### ISSUE TITLE
Broken compilation with steamworks 1.38

### ISSUE THREAD

**Issue by ags131** [greenheartgames/greenworks#99]
I'm trying to build greenworks for node 6.9.0, and am getting the following error. (This is during npm install)

```
In file included from ../src/api/steam_api_friends.cc:12:0:
../src/api/steam_api_friends.cc: In function ‘void greenworks::api::{anonymous}::InitFriendRelationship(v8::Handle<v8::Object>)’:
../src/api/steam_api_friends.cc:54:39: error: ‘k_EFriendRelationshipSuggested’ was not declared in this scope
   SET_TYPE(relationship, "Suggested", k_EFriendRelationshipSuggested);
                                       ^
../src/api/steam_api_registry.h:18:23: note: in definition of macro ‘SET_TYPE’
              Nan::New(type))
                       ^
greenworks-linux64.target.mk:127: recipe for target 'Release/obj.target/greenworks-linux64/src/api/steam_api_friends.o' failed
```

**Comment by hokein** [comment]
Which version of steamworks are you using?

**Comment by ags131** [comment]
Most recent, 1.38a

**Comment by hokein** [comment]
@ags131 Yeah, it doesn't compile with 1.38 because steamworks 1.38 havs some breaking API changes. I'd suggest you to use 1.37 at the moment.

**Comment by ags131** [comment]
Ok, thanks!

**Comment by hokein** [comment]
Fixed in #100.
