### ISSUE TITLE
Module Version mismatch with nw 0.15.0

### ISSUE THREAD

**Issue by Baccanno** [greenheartgames/greenworks#71]
Hi, trying to update greenworks with nw to 0.15.0 I get the following error at launch. I guess it has something to do with a node version being updated in the new release

```
Uncaught Error: Module version mismatch. Expected 48, got 47.
VM510:11 Uncaught Error: Module version mismatch. Expected 48, got 47.
Module._extensions..node @ module.js:604
Module.load @ module.js:476
tryModuleLoad @ module.js:435
Module._load @ module.js:427
Module.require @ module.js:486
require @ internal/module.js:20
(anonymous function) @ D:\Development\synchrom-game-sources\build_platforms\Synchrom\win64\data\greenworks.js:17
Module._compile @ module.js:559
Module._extensions..js @ module.js:574
Module.load @ module.js:476
tryModuleLoad @ module.js:435
Module._load @ module.js:427
Module.require @ module.js:486
require @ internal/module.js:20
self.require @ (program):11
self.require @ VM510:11
(anonymous function) @ indexScript.js:26
```

**Comment by Baccanno** [comment]
Trying to build with node@6.2.0 python@2.7 got this, tried `npm install -g nan` still failing

```
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at node.js:333:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

**Comment by Baccanno** [comment]
okay did a `npm install` and seems that configure is not failing anymore however, this happens. 
```
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFramewo rkVersion or PlatformToolset may be set to an invalid version number. [D:\Development\greenworks\build\deps\zlib\minizip.vcxproj]
TRACKER : error TRK0005: échec de localisation de : "CL.exe". Le fichier spécifié est introuvable. [D:\Development\greenworks\build\deps\zlib\minizip.vcxproj]


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFramewo rkVersion or PlatformToolset may be set to an invalid version number. [D:\Development\greenworks\build\deps\zlib\zlib.vcxproj]
TRACKER : error TRK0005: échec de localisation de : "CL.exe". Le fichier spécifié est introuvable. [D:\Development\greenworks\build\deps\zlib\zlib.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Users\Arch\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arch\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Development\greenworks
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by Baccanno** [comment]
Installed this https://developer.microsoft.com/fr-fr/windows/downloads/windows-8-1-sdk
As in : http://stackoverflow.com/questions/22188919/windows-sdk-registry-variable-not-found

Not working neither, I'm guessing it's a MSbuild version dependency, I got only Msbuild/14.0  and it seems cl.exe no longer exists. Will investigate again later.

**Comment by Baccanno** [comment]
Okay manage to build after installing again visual studio 2015 with visual c++ option activated. I'll PR the documentation then to explain the process on windows for building.

**Comment by hokein** [comment]
@Baccanno 
Glad to see you have figured out the reason. The PR are always welcome :). I'd like close the issue as you have resolved it.
